// Generated by gencpp from file parking_lot_msgs/parking_lot.msg
// DO NOT EDIT!


#ifndef PARKING_LOT_MSGS_MESSAGE_PARKING_LOT_H
#define PARKING_LOT_MSGS_MESSAGE_PARKING_LOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace parking_lot_msgs
{
template <class ContainerAllocator>
struct parking_lot_
{
  typedef parking_lot_<ContainerAllocator> Type;

  parking_lot_()
    : header()
    , corner_left_upper()
    , corner_left_low()
    , corner_right_upper()
    , corner_right_low()
    , center()
    , entrance_center()
    , type(0)
    , is_occupied(0)  {
    }
  parking_lot_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , corner_left_upper(_alloc)
    , corner_left_low(_alloc)
    , corner_right_upper(_alloc)
    , corner_right_low(_alloc)
    , center(_alloc)
    , entrance_center(_alloc)
    , type(0)
    , is_occupied(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner_left_upper_type;
  _corner_left_upper_type corner_left_upper;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner_left_low_type;
  _corner_left_low_type corner_left_low;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner_right_upper_type;
  _corner_right_upper_type corner_right_upper;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner_right_low_type;
  _corner_right_low_type corner_right_low;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _entrance_center_type;
  _entrance_center_type entrance_center;

   typedef int8_t _type_type;
  _type_type type;

   typedef int8_t _is_occupied_type;
  _is_occupied_type is_occupied;





  typedef boost::shared_ptr< ::parking_lot_msgs::parking_lot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parking_lot_msgs::parking_lot_<ContainerAllocator> const> ConstPtr;

}; // struct parking_lot_

typedef ::parking_lot_msgs::parking_lot_<std::allocator<void> > parking_lot;

typedef boost::shared_ptr< ::parking_lot_msgs::parking_lot > parking_lotPtr;
typedef boost::shared_ptr< ::parking_lot_msgs::parking_lot const> parking_lotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parking_lot_msgs::parking_lot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::parking_lot_msgs::parking_lot_<ContainerAllocator1> & lhs, const ::parking_lot_msgs::parking_lot_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.corner_left_upper == rhs.corner_left_upper &&
    lhs.corner_left_low == rhs.corner_left_low &&
    lhs.corner_right_upper == rhs.corner_right_upper &&
    lhs.corner_right_low == rhs.corner_right_low &&
    lhs.center == rhs.center &&
    lhs.entrance_center == rhs.entrance_center &&
    lhs.type == rhs.type &&
    lhs.is_occupied == rhs.is_occupied;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::parking_lot_msgs::parking_lot_<ContainerAllocator1> & lhs, const ::parking_lot_msgs::parking_lot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace parking_lot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parking_lot_msgs::parking_lot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking_lot_msgs::parking_lot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking_lot_msgs::parking_lot_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "577a610f517c24e44cbfed4f97891954";
  }

  static const char* value(const ::parking_lot_msgs::parking_lot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x577a610f517c24e4ULL;
  static const uint64_t static_value2 = 0x4cbfed4f97891954ULL;
};

template<class ContainerAllocator>
struct DataType< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parking_lot_msgs/parking_lot";
  }

  static const char* value(const ::parking_lot_msgs::parking_lot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 全局\n"
"Header header\n"
"\n"
"# 车辆最终泊进车位时 从上往下看\n"
"geometry_msgs/Point corner_left_upper\n"
"geometry_msgs/Point corner_left_low\n"
"geometry_msgs/Point corner_right_upper\n"
"geometry_msgs/Point corner_right_low\n"
"\n"
"geometry_msgs/Point center           # 方块的中心\n"
"geometry_msgs/Point entrance_center  # 入口边的中心\n"
"\n"
"int8 type  # 0- 垂直  1 - 侧方位 \n"
"int8 is_occupied # 0- 无占据 1- 占据\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::parking_lot_msgs::parking_lot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.corner_left_upper);
      stream.next(m.corner_left_low);
      stream.next(m.corner_right_upper);
      stream.next(m.corner_right_low);
      stream.next(m.center);
      stream.next(m.entrance_center);
      stream.next(m.type);
      stream.next(m.is_occupied);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct parking_lot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parking_lot_msgs::parking_lot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parking_lot_msgs::parking_lot_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "corner_left_upper: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner_left_upper);
    s << indent << "corner_left_low: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner_left_low);
    s << indent << "corner_right_upper: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner_right_upper);
    s << indent << "corner_right_low: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner_right_low);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "entrance_center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.entrance_center);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "is_occupied: ";
    Printer<int8_t>::stream(s, indent + "  ", v.is_occupied);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARKING_LOT_MSGS_MESSAGE_PARKING_LOT_H
