# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vehicle_msgs/vehicle_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class vehicle_status(genpy.Message):
  _md5sum = "846750d88d04873a7a68c897999f240c"
  _type = "vehicle_msgs/vehicle_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 head1
uint8 head2
uint8 length
uint8 steering
uint8 brake_status
uint8 pedal_ratio
uint8 gear_position
uint16 speed_left_front
uint16 speed_right_front
uint16 speed_left_rear
uint16 speed_right_rear
uint8 command
uint8 work_mode
uint8 racing_num
uint8 fault_type
uint16 checksum


"""
  __slots__ = ['head1','head2','length','steering','brake_status','pedal_ratio','gear_position','speed_left_front','speed_right_front','speed_left_rear','speed_right_rear','command','work_mode','racing_num','fault_type','checksum']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint16','uint16','uint16','uint16','uint8','uint8','uint8','uint8','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       head1,head2,length,steering,brake_status,pedal_ratio,gear_position,speed_left_front,speed_right_front,speed_left_rear,speed_right_rear,command,work_mode,racing_num,fault_type,checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vehicle_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.head1 is None:
        self.head1 = 0
      if self.head2 is None:
        self.head2 = 0
      if self.length is None:
        self.length = 0
      if self.steering is None:
        self.steering = 0
      if self.brake_status is None:
        self.brake_status = 0
      if self.pedal_ratio is None:
        self.pedal_ratio = 0
      if self.gear_position is None:
        self.gear_position = 0
      if self.speed_left_front is None:
        self.speed_left_front = 0
      if self.speed_right_front is None:
        self.speed_right_front = 0
      if self.speed_left_rear is None:
        self.speed_left_rear = 0
      if self.speed_right_rear is None:
        self.speed_right_rear = 0
      if self.command is None:
        self.command = 0
      if self.work_mode is None:
        self.work_mode = 0
      if self.racing_num is None:
        self.racing_num = 0
      if self.fault_type is None:
        self.fault_type = 0
      if self.checksum is None:
        self.checksum = 0
    else:
      self.head1 = 0
      self.head2 = 0
      self.length = 0
      self.steering = 0
      self.brake_status = 0
      self.pedal_ratio = 0
      self.gear_position = 0
      self.speed_left_front = 0
      self.speed_right_front = 0
      self.speed_left_rear = 0
      self.speed_right_rear = 0
      self.command = 0
      self.work_mode = 0
      self.racing_num = 0
      self.fault_type = 0
      self.checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7B4H4BH().pack(_x.head1, _x.head2, _x.length, _x.steering, _x.brake_status, _x.pedal_ratio, _x.gear_position, _x.speed_left_front, _x.speed_right_front, _x.speed_left_rear, _x.speed_right_rear, _x.command, _x.work_mode, _x.racing_num, _x.fault_type, _x.checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.head1, _x.head2, _x.length, _x.steering, _x.brake_status, _x.pedal_ratio, _x.gear_position, _x.speed_left_front, _x.speed_right_front, _x.speed_left_rear, _x.speed_right_rear, _x.command, _x.work_mode, _x.racing_num, _x.fault_type, _x.checksum,) = _get_struct_7B4H4BH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7B4H4BH().pack(_x.head1, _x.head2, _x.length, _x.steering, _x.brake_status, _x.pedal_ratio, _x.gear_position, _x.speed_left_front, _x.speed_right_front, _x.speed_left_rear, _x.speed_right_rear, _x.command, _x.work_mode, _x.racing_num, _x.fault_type, _x.checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.head1, _x.head2, _x.length, _x.steering, _x.brake_status, _x.pedal_ratio, _x.gear_position, _x.speed_left_front, _x.speed_right_front, _x.speed_left_rear, _x.speed_right_rear, _x.command, _x.work_mode, _x.racing_num, _x.fault_type, _x.checksum,) = _get_struct_7B4H4BH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7B4H4BH = None
def _get_struct_7B4H4BH():
    global _struct_7B4H4BH
    if _struct_7B4H4BH is None:
        _struct_7B4H4BH = struct.Struct("<7B4H4BH")
    return _struct_7B4H4BH
