(cl:in-package vehicle_msgs-msg)
(cl:export '(ACCPED-VAL
          ACCPED
          ACCPED_ENABLE-VAL
          ACCPED_ENABLE
          ADM_FAULTLEVEL-VAL
          ADM_FAULTLEVEL
          FOG_LIGHT-VAL
          FOG_LIGHT
          HORN-VAL
          HORN
          HYDRAULIC_BRAKE-VAL
          HYDRAULIC_BRAKE
          HIGH_BEAMLIGH-VAL
          HIGH_BEAMLIGH
          LOW_BEAMLIGHT-VAL
          LOW_BEAMLIGHT
          TURN_SIGNAL-VAL
          TURN_SIGNAL
          DOUBLE_LIGHT-VAL
          DOUBLE_LIGHT
          NIGHT_LIGHT-VAL
          NIGHT_LIGHT
          DEFROSTER_CONTROL-VAL
          DEFROSTER_CONTROL
          WIPER_CONTROL-VAL
          WIPER_CONTROL
          AMBLE_BRAKE-VAL
          AMBLE_BRAKE
          COMPARTMENT_CONTROL-VAL
          COMPARTMENT_CONTROL
          EMERGENCY_BRAKE-VAL
          EMERGENCY_BRAKE
          LOAD_BRAKE-VAL
          LOAD_BRAKE
          ENGINE_START-VAL
          ENGINE_START
          ENGINE_STOP-VAL
          ENGINE_STOP
          ROAD_DRYORWET-VAL
          ROAD_DRYORWET
          SWITCH_DYNAMICORECONOMICAL-VAL
          SWITCH_DYNAMICORECONOMICAL
          SLOPE-VAL
          SLOPE
          GEAR-VAL
          GEAR
          GPS1_CURVATURE_CMD-VAL
          GPS1_CURVATURE_CMD
          FINISH_OVER-VAL
          FINISH_OVER
))