(cl:in-package vehicle_msgs-msg)
(cl:export '(HEAD1-VAL
          HEAD1
          HEAD2-VAL
          HEAD2
          LENGTH-VAL
          LENGTH
          STEERING-VAL
          STEERING
          BRAKE_STATUS-VAL
          BRAKE_STATUS
          PEDAL_RATIO-VAL
          PEDAL_RATIO
          GEAR_POSITION-VAL
          GEAR_POSITION
          SPEED_LEFT_FRONT-VAL
          SPEED_LEFT_FRONT
          SPEED_RIGHT_FRONT-VAL
          SPEED_RIGHT_FRONT
          SPEED_LEFT_REAR-VAL
          SPEED_LEFT_REAR
          SPEED_RIGHT_REAR-VAL
          SPEED_RIGHT_REAR
          COMMAND-VAL
          COMMAND
          WORK_MODE-VAL
          WORK_MODE
          RACING_NUM-VAL
          RACING_NUM
          FAULT_TYPE-VAL
          FAULT_TYPE
          CHECKSUM-VAL
          CHECKSUM
))