(cl:in-package vehicle_msgs-msg)
(cl:export '(VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          VEHICLE_SPEEDQUALITY-VAL
          VEHICLE_SPEEDQUALITY
          EPS_STEERANG-VAL
          EPS_STEERANG
          EPS_STEERANGQUALITY-VAL
          EPS_STEERANGQUALITY
          BMS_BATTSOC-VAL
          BMS_BATTSOC
          BMS_BATTSOCQUALITY-VAL
          BMS_BATTSOCQUALITY
          TAR_GEARFEED-VAL
          TAR_GEARFEED
          TAR_GEARFEEDQUALITY-VAL
          TAR_GEARFEEDQUALITY
          DRIVE_MODE-VAL
          DRIVE_MODE
))