(cl:in-package vehicle_msgs-msg)
(cl:export '(TARACCLER-VAL
          TARACCLER
          TAR_STEERANGLE-VAL
          TAR_STEERANGLE
          TAR_GEAR-VAL
          TAR_GEAR
          DIVEOFFREQ-VAL
          DIVEOFFREQ
          ADS_MODE-VAL
          ADS_MODE
          STOPREQUEST-VAL
          STOPREQUEST
          ENDOFTRAVEL-VAL
          ENDOFTRAVEL
          STATION_IN_OUT-VAL
          STATION_IN_OUT
          TURNSIGNAL-VAL
          TURNSIGNAL
          DOUBLELIGHT-VAL
          DOUBLELIGHT
          HUMMERSTS-VAL
          HUMMERSTS
          LATACCELERATION-VAL
          LATACCELERATION
          LONGACCELERATION-VAL
          LONGACCELERATION
          ACCELERATION-VAL
          ACCELERATION
          YAW_RATE-VAL
          YAW_RATE
          SLOPE-VAL
          SLOPE
))