(cl:in-package location_msgs-msg)
(cl:export '(STATUS-VAL
          STATUS
          STAMP-VAL
          STAMP
          GPSTIME-VAL
          GPSTIME
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEIGHT-VAL
          HEIGHT
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          VELOCITY-VAL
          VELOCITY
          ACCELRAWX-VAL
          ACCELRAWX
          ACCELRAWY-VAL
          ACCELRAWY
          ACCELRAWZ-VAL
          ACCELRAWZ
          ANGRATERAWX-VAL
          ANGRATERAWX
          ANGRATERAWY-VAL
          ANGRATERAWY
          ANGRATERAWZ-VAL
          ANGRATERAWZ
))