(cl:in-package can_decode-msg)
(cl:export '(STAMP-VAL
          STAMP
          GPSTIME-VAL
          GPSTIME
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEIGHT-VAL
          HEIGHT
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          ANGRATERAWX-VAL
          ANGRATERAWX
          ANGRATERAWY-VAL
          ANGRATERAWY
          ANGRATERAWZ-VAL
          ANGRATERAWZ
          ACCELRAWX-VAL
          ACCELRAWX
          ACCELRAWY-VAL
          ACCELRAWY
          ACCELRAWZ-VAL
          ACCELRAWZ
))